apiVersion: v1
kind: Secret
metadata:
  name: asumi-29-secret
  namespace: asumi-29-namespace
  labels:
    app: asumi-29

type: Opaque
data:
  username: c2E=
  password: cGFzc3dvcmQ=
  app_port: OTA5MA==
