apiVersion: v1
kind: Secret
metadata:
  name: producto-29-secret
  namespace: producto-29-namespace
  labels:
    app: producto-29

type: Opaque
data:
  username: c2E=
  password: cGFzc3dvcmQ=
  app_port: ODA4MA==
