apiVersion: v1
kind: Service
metadata:
  name: producto-29-service
  namespace: producto-29-namespace
  labels:
    app: producto-29
spec:
  selector:
    app: producto-29
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30081
